// List of vague quantifiers
export const vagueQuantifiers = [
  "All",
  "None",
  "Almost all",
  "Most",
  "The majority",
  "A couple",
  "Several",
  "A few",
  "A handful",
  "Some",
  "Many",
  "A lot",
  "Few",
  // "Multiple",
  // "A Little",
  // "Numerous",
  // "A Smattering",
  // "A Sprinkling",
  // "A Majority",
  // "Scads",
  // "A Slew",
  // "Every",
  // "Nearly All",
  // "Virtually All",
  // "Hardly Any",
  // "Barely Any",
];
