// List of vague quantifiers
export default [
  "All",
  "None",
  "Some",
  "A few",
  "Several",
  "Almost all",
  "Most",
  "A couple",
  "A majority",
  "A handful",
  "Many",
  "A lot",
  // "Hardly any",
  // "Scads",
  // "Multiple",
  // "A Little",
  // "Numerous",
  // "A Smattering",
  // "A Sprinkling",
  // "A Slew",
  // "Nearly All",
  // "Virtually All",
  // "Barely Any",
];
